# Generated by Django 4.2.11 on 2024-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmerprofile',
            name='experience',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Mid', 'Mid'), ('Senior', 'Senior')], max_length=100),
        ),
    ]
