# Generated by Django 4.2.11 on 2024-04-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmers', '0002_alter_programmerprofile_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmerprofile',
            name='experience',
            field=models.CharField(choices=[('Mid', 'Mid'), ('Senior', 'Senior'), ('Junior', 'Junior')], max_length=100),
        ),
    ]
