# Generated by Django 4.2.11 on 2024-04-13 08:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0002_rename_communicate_usermessage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMessage',
            new_name='Message',
        ),
    ]
