# Generated by Django 4.2.11 on 2024-03-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programerprofile',
            old_name='code_skils',
            new_name='programming_languages',
        ),
        migrations.AlterField(
            model_name='programerprofile',
            name='experience',
            field=models.CharField(choices=[('JUNIOR', 'JUNIOR'), ('MIDDLE', 'MIDDLE'), ('SENIOR', 'SENIOR')], max_length=100),
        ),
    ]
