# Generated by Django 4.2.11 on 2024-03-25 21:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_code_skils_programerprofile_programming_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programerprofile',
            name='frameworks',
        ),
        migrations.AddField(
            model_name='programerprofile',
            name='tech_stack',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Django', 'Django'), ('Celery', 'Celery'), ('Flask', 'Flask'), ('FastAPI', 'FastAPI'), ('Databases', 'Databases'), ('Docker', 'Docker'), ('Git | GitHub', 'Git | GitHub')], default='Django', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programerprofile',
            name='experience',
            field=models.CharField(choices=[('Mid', 'Mid'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=100),
        ),
        migrations.AlterField(
            model_name='programerprofile',
            name='programming_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Java', 'Java'), ('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('R', 'R'), ('PHP', 'PHP'), ('SQL', 'SQL')], max_length=500),
        ),
    ]
